# Mòdul 3 - Exercicis

## Parte 1
#### En aquesta tasca treballaràs amb la llibreria numpy i amb les dades de la llibreria sklearn.datasets. D'aquesta llibreria descarrega el conjunt de dades denominat Iris. 
#### Tingues en compte que Iris està conformada per diversos conjunts de dades, dins d'ells, el array denominat: “data” i “target”. També està composta per llistes, per exemple: “feature_*names” i “target_*names”. 
#### Per a obtenir informació del dataset pots consultar el següent enllaç:
[https://scikit-learn.org/stable/modules/generated/sklearn.datasets.load_iris.html]

### Exercici 1: Carregar “data” i "target" del conjunt de dades, i visualitza els 10 primers registres de cadascun.

In [69]:
import numpy as np
import sklearn
from sklearn.datasets import load_iris

In [70]:
iris = load_iris()
data = iris.data
target = iris.target

In [71]:
iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
        [5.5, 4.2, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.2],
        [5. , 3.2, 1.2, 0.2],
        [5.5, 3.5, 1.3, 0.2],
        [4.9, 3.6, 1.4, 0.1],
        [4.4, 3. , 1.3, 0.2],
        [5.1, 3.4, 1.5, 0.2],
        [5. , 3.5, 1.3, 0.3],
        [4.5, 2.3, 1.3, 0.3],
        [4.4, 3.2, 1.3, 0.2],
        [5. , 3.5, 1.6, 0.6],
        [5.1, 3.8, 1.9, 0.4],
        [4.8, 3. , 1.4, 0.3],
        [5.1, 3.8, 1.6, 0.2],
        [4.6, 3.2, 1.4, 0.2],
        [5.3, 3.7, 1.5, 0.2],
        [5. , 3.3, 1.4, 0.2],
        [7. , 3.2, 4.7, 1.4],
        [6.4, 3.2, 4.5, 1.5],
        [6.9, 3.1, 4.9, 1.5],
        [5.5, 2.3, 4. , 1.3],
        [6.5, 2.8, 4.6, 1.5],
        [5.7, 2.8, 4.5, 1.3],
        [6.3, 3.3, 4.7, 1.6],
        [4.9, 2.4, 3.3, 1. ],
        [6.6, 2.9, 4.6, 1.3],
        [5.2, 2.7, 3.9, 1.4],
        [5. , 2. , 3.5, 1. ],
        [5.9, 3. , 4.2, 1.5],
        [6. , 2.2, 4. , 1. ],
        [6.1, 2.9, 4.7, 1.4],
        [5.6, 2.9, 3.6, 1.3],
        [6.7, 3.1, 4.4, 1.4],
        [5.6, 3. , 4.5, 1.5],
        [5.8, 2.7, 4.1, 1. ],
        [6.2, 2.2, 4.5, 1.5],
        [5.6, 2.5, 3.9, 1.1],
        [5.9, 3.2, 4.8, 1.8],
        [6.1, 2.8, 4. , 1.3],
        [6.3, 2.5, 4.9, 1.5],
        [6.1, 2.8, 4.7, 1.2],
        [6.4, 2.9, 4.3, 1.3],
        [6.6, 3. , 4.4, 1.4],
        [6.8, 2.8, 4.8, 1.4],
        [6.7, 3. , 5. , 1.7],
        [6. , 2.9, 4.5, 1.5],
        [5.7, 2.6, 3.5, 1. ],
        [5.5, 2.4, 3.8, 1.1],
        [5.5, 2.4, 3.7, 1. ],
        [5.8, 2.7, 3.9, 1.2],
        [6. , 2.7, 5.1, 1.6],
        [5.4, 3. , 4.5, 1.5],
        [6. , 3.4, 4.5, 1.6],
        [6.7, 3.1, 4.7, 1.5],
        [6.3, 2.3, 4.4, 1.3],
        [5.6, 3. , 4.1, 1.3],
        [5.5, 2.5, 4. , 1.3],
        [5.5, 2.6, 4.4, 1.2],
        [6.1, 3. , 4.6, 1.4],
        [5.8, 2.6, 4. , 1.2],
        [5. , 2.3, 3.3, 1. ],
        [5.6, 2.7, 4.2, 1.3],
        [5.7, 3. , 4.2, 1.2],
        [5.7, 2.9, 4.2, 1.3],
        [6.2, 2.9, 4.3, 1.3],
        [5.1, 2.5, 3. , 1.1],
        [5.7, 2.8, 4.1, 1.3],
        [6.3, 3.3, 6. , 2.5],
        [5.8, 2.7, 5.1, 1.9],
        [7.1, 3. , 5.9, 2.1],
        [6.3, 2.9, 5.6, 1.8],
        [6.5, 3. , 5.8, 2.2],
        [7.6, 3. , 6.6, 2.1],
        [4.9, 2.5, 4.5, 1.7],
        [7.3, 2.9, 6.3, 1.8],
        [6.7, 2.5, 5.8, 1.8],
        [7.2, 3.6, 6.1, 2.5],
        [6.5, 3.2, 5.1, 2. ],
        [6.4, 2.7, 5.3, 1.9],
        [6.8, 3. , 5.5, 2.1],
        [5.7, 2.5, 5. , 2. ],
        [5.8, 2.8, 5.1, 2.4],
        [6.4, 3.2, 5.3, 2.3],
        [6.5, 3. , 5.5, 1.8],
        [7.7, 3.8, 6.7, 2.2],
        [7.7, 2.6, 6.9, 2.3],
        [6. , 2.2, 5. , 1.5],
        [6.9, 3.2, 5.7, 2.3],
        [5.6, 2.8, 4.9, 2. ],
        [7.7, 2.8, 6.7, 2. ],
        [6.3, 2.7, 4.9, 1.8],
        [6.7, 3.3, 5.7, 2.1],
        [7.2, 3.2, 6. , 1.8],
        [6.2, 2.8, 4.8, 1.8],
        [6.1, 3. , 4.9, 1.8],
        [6.4, 2.8, 5.6, 2.1],
        [7.2, 3. , 5.8, 1.6],
        [7.4, 2.8, 6.1, 1.9],
        [7.9, 3.8, 6.4, 2. ],
        [6.4, 2.8, 5.6, 2.2],
        [6.3, 2.8, 5.1, 1.5],
        [6.1, 2.6, 5.6, 1.4],
        [7.7, 3. , 6.1, 2.3],
        [6.3, 3.4, 5.6, 2.4],
        [6.4, 3.1, 5.5, 1.8],
        [6. , 3. , 4.8, 1.8],
        [6.9, 3.1, 5.4, 2.1],
        [6.7, 3.1, 5.6, 2.4],
        [6.9, 3.1, 5.1, 2.3],
        [5.8, 2.7, 5.1, 1.9],
        [6.8, 3.2, 5.9, 2.3],
        [6.7, 3.3, 5.7, 2.5],
        [6.7, 3. , 5.2, 2.3],
        [6.3, 2.5, 5. , 1.9],
        [6.5, 3. , 5.2, 2. ],
        [6.2, 3.4, 5.4, 2.3],
        [5.9, 3. , 5.1, 1.8]]),
 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]),
 'frame': None,
 'target_names': array(['setosa', 'versicolor', 'virginica'], dtype='<U10'),
 'DESCR': '.. _iris_dataset:\n\nIris plants dataset\n--------------------\n\n**Data Set Characteristics:**\n\n    :Number of Instances: 150 (50 in each of three classes)\n    :Number of Attributes: 4 numeric, predictive attributes and the class\n    :Attribute Information:\n        - sepal length in cm\n        - sepal width in cm\n        - petal length in cm\n        - petal width in cm\n        - class:\n                - Iris-Setosa\n                - Iris-Versicolour\n                - Iris-Virginica\n                \n    :Summary Statistics:\n\n    ============== ==== ==== ======= ===== ====================\n                    Min  Max   Mean    SD   Class Correlation\n    ============== ==== ==== ======= ===== ====================\n    sepal length:   4.3  7.9   5.84   0.83    0.7826\n    sepal width:    2.0  4.4   3.05   0.43   -0.4194\n    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)\n    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)\n    ============== ==== ==== ======= ===== ====================\n\n    :Missing Attribute Values: None\n    :Class Distribution: 33.3% for each of 3 classes.\n    :Creator: R.A. Fisher\n    :Donor: Michael Marshall (MARSHALL%PLU@io.arc.nasa.gov)\n    :Date: July, 1988\n\nThe famous Iris database, first used by Sir R.A. Fisher. The dataset is taken\nfrom Fisher\'s paper. Note that it\'s the same as in R, but not as in the UCI\nMachine Learning Repository, which has two wrong data points.\n\nThis is perhaps the best known database to be found in the\npattern recognition literature.  Fisher\'s paper is a classic in the field and\nis referenced frequently to this day.  (See Duda & Hart, for example.)  The\ndata set contains 3 classes of 50 instances each, where each class refers to a\ntype of iris plant.  One class is linearly separable from the other 2; the\nlatter are NOT linearly separable from each other.\n\n.. topic:: References\n\n   - Fisher, R.A. "The use of multiple measurements in taxonomic problems"\n     Annual Eugenics, 7, Part II, 179-188 (1936); also in "Contributions to\n     Mathematical Statistics" (John Wiley, NY, 1950).\n   - Duda, R.O., & Hart, P.E. (1973) Pattern Classification and Scene Analysis.\n     (Q327.D83) John Wiley & Sons.  ISBN 0-471-22361-1.  See page 218.\n   - Dasarathy, B.V. (1980) "Nosing Around the Neighborhood: A New System\n     Structure and Classification Rule for Recognition in Partially Exposed\n     Environments".  IEEE Transactions on Pattern Analysis and Machine\n     Intelligence, Vol. PAMI-2, No. 1, 67-71.\n   - Gates, G.W. (1972) "The Reduced Nearest Neighbor Rule".  IEEE Transactions\n     on Information Theory, May 1972, 431-433.\n   - See also: 1988 MLC Proceedings, 54-64.  Cheeseman et al"s AUTOCLASS II\n     conceptual clustering system finds 3 classes in the data.\n   - Many, many more ...',
 'feature_names': ['sepal length (cm)',
  'sepal width (cm)',
  'petal length (cm)',
  'petal width (cm)'],
 'filename': 'iris.csv',
 'data_module': 'sklearn.datasets.data'}

In [72]:
target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [73]:
data[:10]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1]])

In [74]:
target[:10]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Exercici 2: Concatena “data” i “target” en un nou array. Mostra els 5 primers registres.

In [75]:
data.shape

(150, 4)

In [76]:
target.shape

(150,)

In [77]:
np.shape(target.reshape(-1, 1))

(150, 1)

In [78]:
matriu_iris = np.concatenate((data, target.reshape(-1, 1)), axis = 1)
matriu_iris

array([[5.1, 3.5, 1.4, 0.2, 0. ],
       [4.9, 3. , 1.4, 0.2, 0. ],
       [4.7, 3.2, 1.3, 0.2, 0. ],
       [4.6, 3.1, 1.5, 0.2, 0. ],
       [5. , 3.6, 1.4, 0.2, 0. ],
       [5.4, 3.9, 1.7, 0.4, 0. ],
       [4.6, 3.4, 1.4, 0.3, 0. ],
       [5. , 3.4, 1.5, 0.2, 0. ],
       [4.4, 2.9, 1.4, 0.2, 0. ],
       [4.9, 3.1, 1.5, 0.1, 0. ],
       [5.4, 3.7, 1.5, 0.2, 0. ],
       [4.8, 3.4, 1.6, 0.2, 0. ],
       [4.8, 3. , 1.4, 0.1, 0. ],
       [4.3, 3. , 1.1, 0.1, 0. ],
       [5.8, 4. , 1.2, 0.2, 0. ],
       [5.7, 4.4, 1.5, 0.4, 0. ],
       [5.4, 3.9, 1.3, 0.4, 0. ],
       [5.1, 3.5, 1.4, 0.3, 0. ],
       [5.7, 3.8, 1.7, 0.3, 0. ],
       [5.1, 3.8, 1.5, 0.3, 0. ],
       [5.4, 3.4, 1.7, 0.2, 0. ],
       [5.1, 3.7, 1.5, 0.4, 0. ],
       [4.6, 3.6, 1. , 0.2, 0. ],
       [5.1, 3.3, 1.7, 0.5, 0. ],
       [4.8, 3.4, 1.9, 0.2, 0. ],
       [5. , 3. , 1.6, 0.2, 0. ],
       [5. , 3.4, 1.6, 0.4, 0. ],
       [5.2, 3.5, 1.5, 0.2, 0. ],
       [5.2, 3.4, 1.4, 0.2, 0. ],
       [4.7, 3.2, 1.6, 0.2, 0. ],
       [4.8, 3.1, 1.6, 0.2, 0. ],
       [5.4, 3.4, 1.5, 0.4, 0. ],
       [5.2, 4.1, 1.5, 0.1, 0. ],
       [5.5, 4.2, 1.4, 0.2, 0. ],
       [4.9, 3.1, 1.5, 0.2, 0. ],
       [5. , 3.2, 1.2, 0.2, 0. ],
       [5.5, 3.5, 1.3, 0.2, 0. ],
       [4.9, 3.6, 1.4, 0.1, 0. ],
       [4.4, 3. , 1.3, 0.2, 0. ],
       [5.1, 3.4, 1.5, 0.2, 0. ],
       [5. , 3.5, 1.3, 0.3, 0. ],
       [4.5, 2.3, 1.3, 0.3, 0. ],
       [4.4, 3.2, 1.3, 0.2, 0. ],
       [5. , 3.5, 1.6, 0.6, 0. ],
       [5.1, 3.8, 1.9, 0.4, 0. ],
       [4.8, 3. , 1.4, 0.3, 0. ],
       [5.1, 3.8, 1.6, 0.2, 0. ],
       [4.6, 3.2, 1.4, 0.2, 0. ],
       [5.3, 3.7, 1.5, 0.2, 0. ],
       [5. , 3.3, 1.4, 0.2, 0. ],
       [7. , 3.2, 4.7, 1.4, 1. ],
       [6.4, 3.2, 4.5, 1.5, 1. ],
       [6.9, 3.1, 4.9, 1.5, 1. ],
       [5.5, 2.3, 4. , 1.3, 1. ],
       [6.5, 2.8, 4.6, 1.5, 1. ],
       [5.7, 2.8, 4.5, 1.3, 1. ],
       [6.3, 3.3, 4.7, 1.6, 1. ],
       [4.9, 2.4, 3.3, 1. , 1. ],
       [6.6, 2.9, 4.6, 1.3, 1. ],
       [5.2, 2.7, 3.9, 1.4, 1. ],
       [5. , 2. , 3.5, 1. , 1. ],
       [5.9, 3. , 4.2, 1.5, 1. ],
       [6. , 2.2, 4. , 1. , 1. ],
       [6.1, 2.9, 4.7, 1.4, 1. ],
       [5.6, 2.9, 3.6, 1.3, 1. ],
       [6.7, 3.1, 4.4, 1.4, 1. ],
       [5.6, 3. , 4.5, 1.5, 1. ],
       [5.8, 2.7, 4.1, 1. , 1. ],
       [6.2, 2.2, 4.5, 1.5, 1. ],
       [5.6, 2.5, 3.9, 1.1, 1. ],
       [5.9, 3.2, 4.8, 1.8, 1. ],
       [6.1, 2.8, 4. , 1.3, 1. ],
       [6.3, 2.5, 4.9, 1.5, 1. ],
       [6.1, 2.8, 4.7, 1.2, 1. ],
       [6.4, 2.9, 4.3, 1.3, 1. ],
       [6.6, 3. , 4.4, 1.4, 1. ],
       [6.8, 2.8, 4.8, 1.4, 1. ],
       [6.7, 3. , 5. , 1.7, 1. ],
       [6. , 2.9, 4.5, 1.5, 1. ],
       [5.7, 2.6, 3.5, 1. , 1. ],
       [5.5, 2.4, 3.8, 1.1, 1. ],
       [5.5, 2.4, 3.7, 1. , 1. ],
       [5.8, 2.7, 3.9, 1.2, 1. ],
       [6. , 2.7, 5.1, 1.6, 1. ],
       [5.4, 3. , 4.5, 1.5, 1. ],
       [6. , 3.4, 4.5, 1.6, 1. ],
       [6.7, 3.1, 4.7, 1.5, 1. ],
       [6.3, 2.3, 4.4, 1.3, 1. ],
       [5.6, 3. , 4.1, 1.3, 1. ],
       [5.5, 2.5, 4. , 1.3, 1. ],
       [5.5, 2.6, 4.4, 1.2, 1. ],
       [6.1, 3. , 4.6, 1.4, 1. ],
       [5.8, 2.6, 4. , 1.2, 1. ],
       [5. , 2.3, 3.3, 1. , 1. ],
       [5.6, 2.7, 4.2, 1.3, 1. ],
       [5.7, 3. , 4.2, 1.2, 1. ],
       [5.7, 2.9, 4.2, 1.3, 1. ],
       [6.2, 2.9, 4.3, 1.3, 1. ],
       [5.1, 2.5, 3. , 1.1, 1. ],
       [5.7, 2.8, 4.1, 1.3, 1. ],
       [6.3, 3.3, 6. , 2.5, 2. ],
       [5.8, 2.7, 5.1, 1.9, 2. ],
       [7.1, 3. , 5.9, 2.1, 2. ],
       [6.3, 2.9, 5.6, 1.8, 2. ],
       [6.5, 3. , 5.8, 2.2, 2. ],
       [7.6, 3. , 6.6, 2.1, 2. ],
       [4.9, 2.5, 4.5, 1.7, 2. ],
       [7.3, 2.9, 6.3, 1.8, 2. ],
       [6.7, 2.5, 5.8, 1.8, 2. ],
       [7.2, 3.6, 6.1, 2.5, 2. ],
       [6.5, 3.2, 5.1, 2. , 2. ],
       [6.4, 2.7, 5.3, 1.9, 2. ],
       [6.8, 3. , 5.5, 2.1, 2. ],
       [5.7, 2.5, 5. , 2. , 2. ],
       [5.8, 2.8, 5.1, 2.4, 2. ],
       [6.4, 3.2, 5.3, 2.3, 2. ],
       [6.5, 3. , 5.5, 1.8, 2. ],
       [7.7, 3.8, 6.7, 2.2, 2. ],
       [7.7, 2.6, 6.9, 2.3, 2. ],
       [6. , 2.2, 5. , 1.5, 2. ],
       [6.9, 3.2, 5.7, 2.3, 2. ],
       [5.6, 2.8, 4.9, 2. , 2. ],
       [7.7, 2.8, 6.7, 2. , 2. ],
       [6.3, 2.7, 4.9, 1.8, 2. ],
       [6.7, 3.3, 5.7, 2.1, 2. ],
       [7.2, 3.2, 6. , 1.8, 2. ],
       [6.2, 2.8, 4.8, 1.8, 2. ],
       [6.1, 3. , 4.9, 1.8, 2. ],
       [6.4, 2.8, 5.6, 2.1, 2. ],
       [7.2, 3. , 5.8, 1.6, 2. ],
       [7.4, 2.8, 6.1, 1.9, 2. ],
       [7.9, 3.8, 6.4, 2. , 2. ],
       [6.4, 2.8, 5.6, 2.2, 2. ],
       [6.3, 2.8, 5.1, 1.5, 2. ],
       [6.1, 2.6, 5.6, 1.4, 2. ],
       [7.7, 3. , 6.1, 2.3, 2. ],
       [6.3, 3.4, 5.6, 2.4, 2. ],
       [6.4, 3.1, 5.5, 1.8, 2. ],
       [6. , 3. , 4.8, 1.8, 2. ],
       [6.9, 3.1, 5.4, 2.1, 2. ],
       [6.7, 3.1, 5.6, 2.4, 2. ],
       [6.9, 3.1, 5.1, 2.3, 2. ],
       [5.8, 2.7, 5.1, 1.9, 2. ],
       [6.8, 3.2, 5.9, 2.3, 2. ],
       [6.7, 3.3, 5.7, 2.5, 2. ],
       [6.7, 3. , 5.2, 2.3, 2. ],
       [6.3, 2.5, 5. , 1.9, 2. ],
       [6.5, 3. , 5.2, 2. , 2. ],
       [6.2, 3.4, 5.4, 2.3, 2. ],
       [5.9, 3. , 5.1, 1.8, 2. ]])

In [79]:
matriu_iris[:5]

array([[5.1, 3.5, 1.4, 0.2, 0. ],
       [4.9, 3. , 1.4, 0.2, 0. ],
       [4.7, 3.2, 1.3, 0.2, 0. ],
       [4.6, 3.1, 1.5, 0.2, 0. ],
       [5. , 3.6, 1.4, 0.2, 0. ]])

### Exercici 3: Calcula la mitjana i desviació estàndard de la longitud del sèpal ("sepal length (cm)") i la longitud del pètal ("petal length (cm)"). Mostra els resultats amb dos decimals.

In [80]:
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [81]:
iris.feature_names[0]

'sepal length (cm)'

In [82]:
iris.feature_names[2]

'petal length (cm)'

In [83]:
for i in [0, 2]:
    print(f'mitjana de {iris.feature_names[i]} es {round(np.mean(matriu_iris[:, i]), 2)}')
    print(f'desviació estàndard de {iris.feature_names[i]} es {round(np.std(matriu_iris[:, i]), 2)}')

mitjana de sepal length (cm) es 5.84
desviació estàndard de sepal length (cm) es 0.83
mitjana de petal length (cm) es 3.76
desviació estàndard de petal length (cm) es 1.76

### Exercici 4: Selecciona una mostra aleatòria de 20 registres del conjunt que has obtingut en l'exercici anterior. La utilitzaràs d'aquí endavant.

In [84]:
len(matriu_iris)

150

In [85]:
np.random.choice(len(matriu_iris), size = 20, replace = False)

array([133, 116,  62, 105,  31,  48,  65,  92,   0,  24,  50,   8,  86,
        98,  44, 136,  64,  22, 114,  93])

In [86]:
mostra_aleatoria_iris = matriu_iris[np.random.choice(len(matriu_iris), size = 20, replace = False), :]
mostra_aleatoria_iris

array([[6.8, 3.2, 5.9, 2.3, 2. ],
       [6.3, 3.4, 5.6, 2.4, 2. ],
       [6.2, 2.9, 4.3, 1.3, 1. ],
       [5.4, 3.9, 1.7, 0.4, 0. ],
       [5.5, 2.4, 3.8, 1.1, 1. ],
       [6.7, 3.3, 5.7, 2.1, 2. ],
       [6.1, 2.8, 4.7, 1.2, 1. ],
       [5.8, 2.7, 5.1, 1.9, 2. ],
       [4.9, 3.1, 1.5, 0.1, 0. ],
       [5. , 2. , 3.5, 1. , 1. ],
       [4.4, 3.2, 1.3, 0.2, 0. ],
       [5.1, 3.7, 1.5, 0.4, 0. ],
       [4.6, 3.1, 1.5, 0.2, 0. ],
       [6.2, 3.4, 5.4, 2.3, 2. ],
       [7.2, 3. , 5.8, 1.6, 2. ],
       [5.5, 2.4, 3.7, 1. , 1. ],
       [7.2, 3.6, 6.1, 2.5, 2. ],
       [4.9, 2.4, 3.3, 1. , 1. ],
       [5.1, 2.5, 3. , 1.1, 1. ],
       [7.7, 3.8, 6.7, 2.2, 2. ]])

In [87]:
len(mostra_aleatoria_iris)

20

### Exercici 5: Crea una matriu que mostri:  
### - La mitjana de cada característica per espècie. (mean)
### - La desviació estàndard de cada característica per espècie. (std)

In [88]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [89]:
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [90]:
ultima = mostra_aleatoria_iris[:, -1]
ultima

array([2., 2., 1., 0., 1., 2., 1., 2., 0., 1., 0., 0., 0., 2., 2., 1., 2.,
       1., 1., 2.])

In [91]:
for especie in range(3):
    subconsulta = mostra_aleatoria_iris [ultima == especie, :-1]
    print(f'{iris.target_names[especie]} mitjana es {np.mean(subconsulta, axis=0)}')
    print(f'{iris.target_names[especie]} desciació estàndard es {np.std(subconsulta, axis=0)}')

setosa mitjana es [4.88 3.4  1.5  0.26]
setosa desciació estàndard es [0.3544009  0.33466401 0.12649111 0.12      ]
versicolor mitjana es [5.47142857 2.48571429 3.75714286 1.1       ]
versicolor desciació estàndard es [0.48022104 0.2747912  0.53946307 0.1069045 ]
virginica mitjana es [6.7375 3.3    5.7875 2.1625]
virginica desciació estàndard es [0.58296119 0.32015621 0.44843478 0.27357586]

### Exercici 6: 
### - Calcula la quantitat de mostres per espècie.
### - Troba l'espècie amb el valor màxim mitjana de la variable "sepal length (cm)"

In [92]:
np.bincount(mostra_aleatoria_iris[:, -1].astype(int))

array([5, 7, 8], dtype=int64)

In [93]:
mitjanes = []
for especie in range(3):
    subconsulta = mostra_aleatoria_iris[ultima == especie, :-1]
    print(f'{iris.target_names[especie]} mitjana es {np.mean(subconsulta, axis=0)}')
    print(f'{iris.target_names[especie]} desviació estàndard es {np.std(subconsulta, axis=0)}')
    mitjanes.append(np.mean(subconsulta, axis=0))

setosa mitjana es [4.88 3.4  1.5  0.26]
setosa desviació estàndard es [0.3544009  0.33466401 0.12649111 0.12      ]
versicolor mitjana es [5.47142857 2.48571429 3.75714286 1.1       ]
versicolor desviació estàndard es [0.48022104 0.2747912  0.53946307 0.1069045 ]
virginica mitjana es [6.7375 3.3    5.7875 2.1625]
virginica desviació estàndard es [0.58296119 0.32015621 0.44843478 0.27357586]

In [94]:
mitjanes

[array([4.88, 3.4 , 1.5 , 0.26]),
 array([5.47142857, 2.48571429, 3.75714286, 1.1       ]),
 array([6.7375, 3.3   , 5.7875, 2.1625])]

In [95]:
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [96]:
mitjanes[:][0]

array([4.88, 3.4 , 1.5 , 0.26])

In [97]:
mitjanes

[array([4.88, 3.4 , 1.5 , 0.26]),
 array([5.47142857, 2.48571429, 3.75714286, 1.1       ]),
 array([6.7375, 3.3   , 5.7875, 2.1625])]

In [98]:
# Cada columna correspon a un parametre caracteristic ('sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)').
# Cada fila correspon a una especie.

iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [99]:
# Veiem que la especie amb la mitjana més gran de longitud de sepal es la setosa
mitjanes [2][0]

6.737500000000001

### Exercici 7 :
### - Calcula la matriu de correlació entre les variables.
### - Filtra els valors majors a la mitjana (de l'exercici 3) de la longitud dels pètals i mostra-ho. 
### - Troba la mostra amb els pètals més llargs.

In [100]:
np.corrcoef(mostra_aleatoria_iris, rowvar=False)

array([[1.        , 0.40021793, 0.91085927, 0.83971316, 0.82315689],
       [0.40021793, 1.        , 0.10433491, 0.19076674, 0.0345016 ],
       [0.91085927, 0.10433491, 1.        , 0.95462237, 0.96846675],
       [0.83971316, 0.19076674, 0.95462237, 1.        , 0.96691563],
       [0.82315689, 0.0345016 , 0.96846675, 0.96691563, 1.        ]])

In [101]:
np.mean(matriu_iris[:, 2])

3.7580000000000005

In [102]:
mostra_aleatoria_iris[:, 2] > np.mean(matriu_iris[:, 2])

array([ True,  True,  True, False,  True,  True,  True,  True, False,
       False, False, False, False,  True,  True, False,  True, False,
       False,  True])

In [103]:
mostra_aleatoria_iris[mostra_aleatoria_iris[:, 2] > np.mean(matriu_iris[:, 2])]

array([[6.8, 3.2, 5.9, 2.3, 2. ],
       [6.3, 3.4, 5.6, 2.4, 2. ],
       [6.2, 2.9, 4.3, 1.3, 1. ],
       [5.5, 2.4, 3.8, 1.1, 1. ],
       [6.7, 3.3, 5.7, 2.1, 2. ],
       [6.1, 2.8, 4.7, 1.2, 1. ],
       [5.8, 2.7, 5.1, 1.9, 2. ],
       [6.2, 3.4, 5.4, 2.3, 2. ],
       [7.2, 3. , 5.8, 1.6, 2. ],
       [7.2, 3.6, 6.1, 2.5, 2. ],
       [7.7, 3.8, 6.7, 2.2, 2. ]])

In [104]:
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [105]:
max(mostra_aleatoria_iris[:, 2])

6.7

In [106]:
np.argmax(mostra_aleatoria_iris[:, 2])

19

In [107]:
mostra_aleatoria_iris[np.argmax(mostra_aleatoria_iris[:, 2])]

array([7.7, 3.8, 6.7, 2.2, 2. ])

## Parte 2: Exercicis amb Dataframes.

In [108]:
import pandas as pd

### Exercici 1: Descarrega el data set Airlines Delay: Airline on-time statistics and delay causes i carrega’l a un Pandas Dataframe. 
### - Explora les dades que conté, explica breument quines variables hi ha i queda’t únicament amb les columnes que consideris rellevants. Justifica la teva elecció.
### - Neteja el data set.
#### Descarrega les dades des d'aquesta adreça: [https://www.kaggle.com/datasets/giovamata/airlinedelaycauses]
##### Important: Redueix la dimensió del dataset de manera aleatòria per tal d'obtenir un dataset de només 200.000 registres. Tots els exercicis s'han de fer amb aquest dataset reduït.

In [109]:
df = pd.read_csv('C:/Users/52715488V/Desktop/Notebook Jupyter/DelayedFlights.csv')

In [110]:
df

,Unnamed: 0,Year,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,...,TaxiIn,TaxiOut,Cancelled,CancellationCode,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
0,0,2008,1,3,4,2003.0,1955,2211.0,2225,WN,...,4.0,8.0,0,N,0,NaN,NaN,NaN,NaN,NaN
1,1,2008,1,3,4,754.0,735,1002.0,1000,WN,...,5.0,10.0,0,N,0,NaN,NaN,NaN,NaN,NaN
2,2,2008,1,3,4,628.0,620,804.0,750,WN,...,3.0,17.0,0,N,0,NaN,NaN,NaN,NaN,NaN
3,4,2008,1,3,4,1829.0,1755,1959.0,1925,WN,...,3.0,10.0,0,N,0,2.0,0.0,0.0,0.0,32.0
4,5,2008,1,3,4,1940.0,1915,2121.0,2110,WN,...,4.0,10.0,0,N,0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1936753,7009710,2008,12,13,6,1250.0,1220,1617.0,1552,DL,...,9.0,18.0,0,N,0,3.0,0.0,0.0,0.0,22.0
1936754,7009717,2008,12,13,6,657.0,600,904.0,749,DL,...,15.0,34.0,0,N,0,0.0,57.0,18.0,0.0,0.0
1936755,7009718,2008,12,13,6,1007.0,847,1149.0,1010,DL,...,8.0,32.0,0,N,0,1.0,0.0,19.0,0.0,79.0
1936756,7009726,2008,12,13,6,1251.0,1240,1446.0,1437,DL,...,13.0,13.0,0,N,0,NaN,NaN,NaN,NaN,NaN
1936757,7009727,2008,12,13,6,1110.0,1103,1413.0,1418,DL,...,8.0,11.0,0,N,0,NaN,NaN,NaN,NaN,NaN

In [111]:
# Reduim la dimensió del dataset a 200000 registres
df2 = df.sample(n=200000, replace=True, random_state=1)
df2

,Unnamed: 0,Year,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,...,TaxiIn,TaxiOut,Cancelled,CancellationCode,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
128037,414451,2008,1,9,3,1129.0,1110,1404.0,1400,MQ,...,5.0,7.0,0,N,0,NaN,NaN,NaN,NaN,NaN
491755,1538254,2008,3,7,5,1527.0,1409,1736.0,1635,FL,...,7.0,16.0,0,N,0,0.0,0.0,0.0,0.0,61.0
470924,1478136,2008,3,1,6,1840.0,1815,1944.0,1920,WN,...,3.0,9.0,0,N,0,0.0,0.0,0.0,0.0,24.0
1840200,6748681,2008,12,23,2,759.0,750,925.0,917,DL,...,6.0,24.0,0,N,0,NaN,NaN,NaN,NaN,NaN
491263,1537095,2008,3,6,4,1539.0,1530,1706.0,1654,FL,...,8.0,12.0,0,N,0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1306060,4373844,2008,8,15,5,1844.0,1720,2005.0,1853,YV,...,3.0,16.0,0,N,0,0.0,0.0,0.0,0.0,72.0
549528,1720868,2008,3,23,7,1407.0,1351,2147.0,2146,AS,...,8.0,14.0,0,N,0,NaN,NaN,NaN,NaN,NaN
928951,3120142,2008,6,27,5,1500.0,1440,1652.0,1638,XE,...,4.0,13.0,0,N,0,NaN,NaN,NaN,NaN,NaN
1771346,6551230,2008,12,30,2,1145.0,1135,1301.0,1255,WN,...,5.0,6.0,0,N,0,NaN,NaN,NaN,NaN,NaN
838009,2826033,2008,5,25,7,1320.0,1304,1550.0,1512,NW,...,13.0,21.0,0,N,0,0.0,0.0,22.0,0.0,16.0

In [112]:
df2.iloc[0]

Unnamed: 0           414451
Year                   2008
Month                     1
DayofMonth                9
DayOfWeek                 3
DepTime              1129.0
CRSDepTime             1110
ArrTime              1404.0
CRSArrTime             1400
UniqueCarrier            MQ
FlightNum              4462
TailNum              N816AE
ActualElapsedTime      95.0
CRSElapsedTime        110.0
AirTime                83.0
ArrDelay                4.0
DepDelay               19.0
Origin                  ORD
Dest                    CLT
Distance                599
TaxiIn                  5.0
TaxiOut                 7.0
Cancelled                 0
CancellationCode          N
Diverted                  0
CarrierDelay            NaN
WeatherDelay            NaN
NASDelay                NaN
SecurityDelay           NaN
LateAircraftDelay       NaN
Name: 128037, dtype: object

#### Mantindrem les columnes: Year, Month, DayofMonth, FlightNum, TailNum, ActualElapsedTime, CRSElapsedTime, AirTime, ArrDelay, DepDelay, Origin, Dest, Distance, TaxiIn, TaxiOut, CarrierDelay, NASDelay, SecurityDelay, LateAircraftDelay.

#### La resta de columnes no inclouen informació rellevant i/o estan buides.

In [113]:
# Eliminem les columnes que considerem innecessaries
df3 = df2.drop(['Unnamed: 0', 'DayOfWeek', 'DepTime','CRSDepTime','ArrTime','CRSArrTime','UniqueCarrier','Cancelled', 'CancellationCode','Diverted'], axis=1)
df3

,Year,Month,DayofMonth,FlightNum,TailNum,ActualElapsedTime,CRSElapsedTime,AirTime,ArrDelay,DepDelay,Origin,Dest,Distance,TaxiIn,TaxiOut,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
128037,2008,1,9,4462,N816AE,95.0,110.0,83.0,4.0,19.0,ORD,CLT,599,5.0,7.0,NaN,NaN,NaN,NaN,NaN
491755,2008,3,7,873,N307AT,189.0,206.0,166.0,61.0,78.0,MCO,MSP,1310,7.0,16.0,0.0,0.0,0.0,0.0,61.0
470924,2008,3,1,878,N625SW,64.0,65.0,52.0,24.0,25.0,LAX,SJC,308,3.0,9.0,0.0,0.0,0.0,0.0,24.0
1840200,2008,12,23,957,N604DL,86.0,87.0,56.0,8.0,9.0,ATL,MCO,403,6.0,24.0,NaN,NaN,NaN,NaN,NaN
491263,2008,3,6,776,N313AT,87.0,84.0,67.0,12.0,9.0,ATL,MCO,403,8.0,12.0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1306060,2008,8,15,7279,N27172,81.0,93.0,62.0,72.0,84.0,IAD,CAE,401,3.0,16.0,0.0,0.0,0.0,0.0,72.0
549528,2008,3,23,2,N559AS,280.0,295.0,258.0,1.0,16.0,SEA,DCA,2329,8.0,14.0,NaN,NaN,NaN,NaN,NaN
928951,2008,6,27,2490,N13538,112.0,118.0,95.0,14.0,20.0,IAH,MCI,643,4.0,13.0,NaN,NaN,NaN,NaN,NaN
1771346,2008,12,30,1932,N665WN,76.0,80.0,65.0,6.0,10.0,LAX,SMF,373,5.0,6.0,NaN,NaN,NaN,NaN,NaN
838009,2008,5,25,717,N337NB,210.0,188.0,176.0,38.0,16.0,BOS,MSP,1124,13.0,21.0,0.0,0.0,22.0,0.0,16.0

In [114]:
# Eliminem les files amb valors nulls (NaN)
df_net = df3.dropna()
df_net

,Year,Month,DayofMonth,FlightNum,TailNum,ActualElapsedTime,CRSElapsedTime,AirTime,ArrDelay,DepDelay,Origin,Dest,Distance,TaxiIn,TaxiOut,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
491755,2008,3,7,873,N307AT,189.0,206.0,166.0,61.0,78.0,MCO,MSP,1310,7.0,16.0,0.0,0.0,0.0,0.0,61.0
470924,2008,3,1,878,N625SW,64.0,65.0,52.0,24.0,25.0,LAX,SJC,308,3.0,9.0,0.0,0.0,0.0,0.0,24.0
73349,2008,1,3,583,N381UA,118.0,141.0,104.0,145.0,168.0,SAN,DEN,853,7.0,7.0,0.0,0.0,0.0,0.0,145.0
1166159,2008,7,17,294,N642AW,74.0,69.0,42.0,15.0,10.0,PHX,LAS,256,8.0,24.0,10.0,0.0,5.0,0.0,0.0
1070016,2008,6,20,811,N31412,250.0,231.0,215.0,40.0,21.0,EWR,IAH,1400,16.0,19.0,21.0,0.0,19.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
583076,2008,4,10,419,N324SW,144.0,170.0,126.0,74.0,100.0,SEA,PHX,1107,6.0,12.0,67.0,0.0,0.0,0.0,7.0
1430969,2008,9,8,743,N239WN,271.0,285.0,236.0,17.0,31.0,LAS,PHL,2176,5.0,30.0,0.0,8.0,0.0,0.0,9.0
981046,2008,6,26,1007,N176UW,113.0,85.0,68.0,45.0,17.0,CLT,PIT,366,9.0,36.0,17.0,0.0,28.0,0.0,0.0
1306060,2008,8,15,7279,N27172,81.0,93.0,62.0,72.0,84.0,IAD,CAE,401,3.0,16.0,0.0,0.0,0.0,0.0,72.0
838009,2008,5,25,717,N337NB,210.0,188.0,176.0,38.0,16.0,BOS,MSP,1124,13.0,21.0,0.0,0.0,22.0,0.0,16.0

In [115]:
df_net.head()

,Year,Month,DayofMonth,FlightNum,TailNum,ActualElapsedTime,CRSElapsedTime,AirTime,ArrDelay,DepDelay,Origin,Dest,Distance,TaxiIn,TaxiOut,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
491755,2008,3,7,873,N307AT,189.0,206.0,166.0,61.0,78.0,MCO,MSP,1310,7.0,16.0,0.0,0.0,0.0,0.0,61.0
470924,2008,3,1,878,N625SW,64.0,65.0,52.0,24.0,25.0,LAX,SJC,308,3.0,9.0,0.0,0.0,0.0,0.0,24.0
73349,2008,1,3,583,N381UA,118.0,141.0,104.0,145.0,168.0,SAN,DEN,853,7.0,7.0,0.0,0.0,0.0,0.0,145.0
1166159,2008,7,17,294,N642AW,74.0,69.0,42.0,15.0,10.0,PHX,LAS,256,8.0,24.0,10.0,0.0,5.0,0.0,0.0
1070016,2008,6,20,811,N31412,250.0,231.0,215.0,40.0,21.0,EWR,IAH,1400,16.0,19.0,21.0,0.0,19.0,0.0,0.0

In [116]:
df_net.iloc[0]

Year                   2008
Month                     3
DayofMonth                7
FlightNum               873
TailNum              N307AT
ActualElapsedTime     189.0
CRSElapsedTime        206.0
AirTime               166.0
ArrDelay               61.0
DepDelay               78.0
Origin                  MCO
Dest                    MSP
Distance               1310
TaxiIn                  7.0
TaxiOut                16.0
CarrierDelay            0.0
WeatherDelay            0.0
NASDelay                0.0
SecurityDelay           0.0
LateAircraftDelay      61.0
Name: 491755, dtype: object

### Exercici 2: Fes un informe complet del dataset:

### - Resumeix estadísticament el dataset i les columnes d’interès. Fes una anàlisi estadístic del que consideris rellevant.
### - Mostra quins son els vols amb més endarreriments acumulats.
### - Quins són els vols més llargs?

In [121]:
# Resumen estadístic del dataset eliminan aquelles columnes que no tenen sentit
df_estad = df_net.drop(['Year', 'Month', 'DayofMonth','FlightNum'], axis=1)
df_estad.describe()

,ActualElapsedTime,CRSElapsedTime,AirTime,ArrDelay,DepDelay,Distance,TaxiIn,TaxiOut,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay,ActualET_minus_CRSET
count,129077.000000,129077.000000,129077.000000,129077.000000,129077.000000,129077.000000,129077.000000,129077.000000,129077.000000,129077.000000,129077.000000,129077.000000,129077.000000,129077.000000
mean,135.103799,131.515909,107.212377,63.251075,59.663186,739.659761,7.286418,20.605003,19.187377,3.824392,14.880668,0.080479,25.278160,3.587889
std,72.254500,69.555077,68.160128,60.781356,59.901571,559.570465,6.023562,16.598051,43.684620,22.034785,33.383577,1.868006,41.989065,18.952917
min,17.000000,19.000000,0.000000,15.000000,6.000000,24.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-66.000000
25%,82.000000,80.000000,58.000000,26.000000,24.000000,334.000000,4.000000,11.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-7.000000
50%,118.000000,115.000000,89.000000,43.000000,41.000000,594.000000,6.000000,16.000000,2.000000,0.000000,1.000000,0.000000,8.000000,0.000000
75%,167.000000,160.000000,135.000000,79.000000,75.000000,967.000000,8.000000,24.000000,21.000000,0.000000,15.000000,0.000000,33.000000,10.000000
max,750.000000,660.000000,664.000000,1655.000000,1597.000000,4962.000000,179.000000,386.000000,1359.000000,1153.000000,1207.000000,216.000000,1254.000000,395.000000

In [118]:
# Per el endarreriment acumulat caldra fer aquesta operació: ActualElapsedTime - CRSElapsedTime
df_net = df_net.assign(ActualET_minus_CRSET=df["ActualElapsedTime"] - df["CRSElapsedTime"])
df_net.head()

,Year,Month,DayofMonth,FlightNum,TailNum,ActualElapsedTime,CRSElapsedTime,AirTime,ArrDelay,DepDelay,...,Dest,Distance,TaxiIn,TaxiOut,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay,ActualET_minus_CRSET
491755,2008,3,7,873,N307AT,189.0,206.0,166.0,61.0,78.0,...,MSP,1310,7.0,16.0,0.0,0.0,0.0,0.0,61.0,-17.0
470924,2008,3,1,878,N625SW,64.0,65.0,52.0,24.0,25.0,...,SJC,308,3.0,9.0,0.0,0.0,0.0,0.0,24.0,-1.0
73349,2008,1,3,583,N381UA,118.0,141.0,104.0,145.0,168.0,...,DEN,853,7.0,7.0,0.0,0.0,0.0,0.0,145.0,-23.0
1166159,2008,7,17,294,N642AW,74.0,69.0,42.0,15.0,10.0,...,LAS,256,8.0,24.0,10.0,0.0,5.0,0.0,0.0,5.0
1070016,2008,6,20,811,N31412,250.0,231.0,215.0,40.0,21.0,...,IAH,1400,16.0,19.0,21.0,0.0,19.0,0.0,0.0,19.0

In [119]:
# Mostrem ordenat de major a menor els endarreriments acumulats dels diferents registres del dataset
df_delay_sorted = df_net.sort_values(by=['ActualET_minus_CRSET'], ascending = False)
df_delay_sorted ['ActualET_minus_CRSET']

1930131    395.0
96006      359.0
1930302    333.0
499484     315.0
1045711    260.0
           ...
1323735    -62.0
628316     -62.0
1930030    -63.0
1130564    -65.0
1665339    -66.0
Name: ActualET_minus_CRSET, Length: 129077, dtype: float64

In [120]:
# Identifiquem el vol que va tenir el endarreriment acumulat més gran: N12318.
df_net.loc[1930131]

Year                      2008
Month                       12
DayofMonth                  10
FlightNum                  616
TailNum                 N12318
ActualElapsedTime        574.0
CRSElapsedTime           179.0
AirTime                  183.0
ArrDelay                 450.0
DepDelay                  55.0
Origin                     IAH
Dest                       MSP
Distance                  1034
TaxiIn                     5.0
TaxiOut                  386.0
CarrierDelay               0.0
WeatherDelay              55.0
NASDelay                 395.0
SecurityDelay              0.0
LateAircraftDelay          0.0
ActualET_minus_CRSET     395.0
Name: 1930131, dtype: object

In [ ]:
# Consultant el numero de cola del avió - TailNum - en Internet: https://www.airfleets.net/ficheapp/plane-b737-23369.htm
# Trobem que N12318 pertany a Continental Airlines i es tracta d'un Boeing 737 - MSN 23369

In [129]:
# Mostrem les distancies recorregudes més llarges, en km., indicant la matricula del avió, el origen i el destí.
df_distance_sorted = df_net.sort_values(by=['Distance'], ascending = False)
df_distance_sorted.loc[:, ['TailNum','Origin','Dest','Distance']]

        TailNum Origin Dest  Distance
1072046  N76054    EWR  HNL      4962
1253766  N67058    EWR  HNL      4962
1922725  N66057    EWR  HNL      4962
876511   N59053    EWR  HNL      4962
1519354  N78060    EWR  HNL      4962
...         ...    ...  ...       ...
1058802  N708AS    WRG  PSG        31
549984   N762AS    PSG  WRG        31
1615911  N775AS    WRG  PSG        31
179182   N56859    SJC  SFO        30
47146    N806CA    IAD  DCA        24

[129077 rows x 4 columns]

### Exercici 3: Exporta el dataset net i amb les noves columnes a Excel.

In [ ]:
# Exportem en format excel el dataset net
df_net.to_excel('C:/Users/52715488V/Desktop/Notebook Jupyter/DelayedFlights_net.xlsx')